name: Update Base Image

on:
  schedule:
    # Check for updates weekly on Sundays at 6 AM UTC
    - cron: '0 6 * * 0'
  workflow_dispatch: # Allow manual triggers

jobs:
  check-for-updates:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for new base image
        id: check_image
        run: |
          # Get current image from Dockerfile
          CURRENT_IMAGE=$(grep "^FROM" Dockerfile | awk '{print $2}')
          echo "current_image=$CURRENT_IMAGE" >> $GITHUB_OUTPUT
          
          # Get latest digest for the image
          LATEST_DIGEST=$(docker run --rm quay.io/skopeo/stable inspect docker://$CURRENT_IMAGE | jq -r '.Digest')
          echo "latest_digest=$LATEST_DIGEST" >> $GITHUB_OUTPUT
          
          # Check if we have a previous digest stored
          if [ -f .github/base-image-digest ]; then
            STORED_DIGEST=$(cat .github/base-image-digest)
            echo "stored_digest=$STORED_DIGEST" >> $GITHUB_OUTPUT
            
            if [ "$LATEST_DIGEST" != "$STORED_DIGEST" ]; then
              echo "needs_update=true" >> $GITHUB_OUTPUT
            else
              echo "needs_update=false" >> $GITHUB_OUTPUT
            fi
          else
            echo "needs_update=true" >> $GITHUB_OUTPUT
          fi

      - name: Update digest file
        if: steps.check_image.outputs.needs_update == 'true'
        run: |
          mkdir -p .github
          echo "${{ steps.check_image.outputs.latest_digest }}" > .github/base-image-digest

      - name: Create Pull Request
        if: steps.check_image.outputs.needs_update == 'true'
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: update base image digest to ${{ steps.check_image.outputs.latest_digest }}"
          title: "Update base image: ${{ steps.check_image.outputs.current_image }}"
          body: |
            ## Base Image Update
            
            A new version of the base image `${{ steps.check_image.outputs.current_image }}` is available.
            
            **Previous digest**: `${{ steps.check_image.outputs.stored_digest }}`
            **New digest**: `${{ steps.check_image.outputs.latest_digest }}`
            
            This PR updates the stored digest to track the latest version.
            
            ### Verification Steps
            - [ ] Review any breaking changes in the base image
            - [ ] Test the application functionality
            - [ ] Verify security updates are applied
            
            Auto-generated by the Update Base Image workflow.
          branch: update-base-image
          delete-branch: true